apiVersion: aksnp.spot.upbound.io/v1alpha1
kind: AksNp
metadata:
  name: crossplane-test
  namespace: crossplane-system
spec:
  forProvider:
    name: "oceanClusterName"
    controllerClusterId: "controllerId"
    aksClusterName: "aksClusterName"
    aksInfrastructureResourceGroupName: "aksInfraResourceName"
    aksRegion: "eastus"
    aksResourceGroupName: "resourceGroupName"
    autoscaler:
      - autoscaleDown:
          - maxScaleDownPercentage: 30
        autoscaleHeadroom:
          - automatic:
              - percentage: 5
        autoscaleIsEnabled: true
        resourceLimits:
          - maxMemoryGib: 1500
            maxVcpu: 750
    scheduling:
      - shutdownHours:
          - isEnabled: true
            timeWindows:
              - Sat:08:00-Sun:08:00
    health :
      - gracePeriod: 600
    availabilityZones:
      - "1"
      - "2"
    maxPodsPerNode: 110
    enableNodePublicIp: false
    osDiskSizeGb: 128
    osDiskType: Managed
    osType: Linux
    minCount: 1
    maxCount: 100
    spotPercentage: 100
    fallbackToOndemand: true
  providerConfigRef:
    name: default